name: Elixir CI

on: [pull_request, push]

env:
  MIX_ENV: test
  CONGRESS_TEST_API_KEY: ${{ secrets.CONGRESS_TEST_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  mix_check:
    name: mix check (Elixir ${{matrix.elixir}}, OTP ${{matrix.otp}})

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.15.0'
            otp: '25.3.22'
          - elixir: '1.7.4'
            otp: '20.3.8'

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache deps and build
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}-git-${{ github.sha }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - name: Fetch deps
        run: mix deps.get

      - name: Remove application build
        run: mix clean

      - name: Compile deps
        run: mix deps.compile

      - name: Compile app
        run: mix compile

      - name: Run check
        run: mix check

      - name: Run test coverage
        run: mix coveralls.github

